dist: trusty

language: cpp

compiler:
    - clang
    
branches:
    - develop
    - UnitTests

addons:
    apt:
        sources:
        - boost-latest
        packages:
        - libboost-thread-dev
        - libboost-test-dev
        - libboost-system-dev

before_script:
    - mkdir build
    - cd build
    - cmake ./..
 
script: make && test/future_test

notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always