dist: trusty

language: cpp

compiler:
    - clang
    - gcc
    
branches:
    - develop
    - UnitTests

addons:
    apt:
        sources:
        - boost-latest
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - gcc-5.3
        - g++-5.3
        - libboost-thread-dev
        - libboost-unit_test_framework-dev
        - libboost-system-dev
            
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always

before_script:
    - mkdir build
    - cd build
    - cmake ./..
 
script: make && test/future_test
