language: objective-c

os: osx

osx_image: xcode8.2

compiler:
  - clang
  - gcc

branches:
  except: /pr\/.*/

before_install:
  - brew update
  - brew outdated conan || brew upgrade conan
  - brew outdated cmake || brew upgrade cmake
  - brew outdated xctool || brew upgrade xctool

script:
    - xcode_setup.sh
    - cd build
    - xcodebuild
    - cd bin # It'd be great if we could just run all the binaries we find in here...
    - future_test
    - serial_queue_test

notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always
  slack: stlab:P23OMUJ8T4Pa05OON0VDYwIf
