sudo: required
dist: trusty

language: cpp

branches:
    - develop
    - UnitTests

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-thread-dev
            - libboost-test-dev
            - libboost-system-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-thread-dev
            - libboost-test-dev
            - libboost-system-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libboost-thread-dev
            - libboost-test-dev
            - libboost-system-dev

            env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-thread-dev
            - libboost-test-dev
            - libboost-system-dev
      env: COMPILER=clang++-3.7

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
    - make
    - test/future_test
    
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always