language: cpp
compiler:
    - clang
    - gcc
branches:
        - develop
        - UnitTests
            
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always

before_script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-5.3 -y
    - sudo apt-get install boost-latest -y
    - sudo apt-get install libboost-thread-dev libboost-unit_test_framework-dev libboost-system-dev -y
    - mkdir build
    - cd build
    - cmake ./..
 
script: make && test/future_test
